# Root directory containing all datasets
root_data_dir: /mnt/nfs/SpatialAI/wai_datasets
# Dataset metadata directory
mapanything_dataset_metadata_dir: /mnt/nfs/SpatialAI/wai_datasets/map-anything/mapanything_dataset_metadata
# Root directory containing pretrained checkpoints for custom models
root_pretrained_checkpoints_dir: /work/weights
# Root directory to log experiments
root_experiments_dir: /home/binbin/gtan/mapanything_experiments
# Root directory containing UniCeption pretrained checkpoints
root_uniception_pretrained_checkpoints_dir: ???
# Root directory containing external benchmark data
external_benchmark_data_root_data_dir: /mnt/nfs/SpatialAI/wai_datasets


